### ISSUE TITLE
Remove [lib] section from rust Cargo.toml template

### ISSUE THREAD

**Issue by brooksmtownsend** [wapc/basic-modules#1]
The following section is included in Cargo.toml for generated `rust` modules:
```
[lib]
crate-type = ["cdylib"]
```

Because various different rust modules can be generated with `wapc`, including ones that should not have the `[lib]` tag, it should be removed from the template and users can add it if they want to make their cargo project a library

**Comment by pkedy** [comment]
@autodidaddict asked me to add this. Being that I'm not a Rust pro yet, I'll defer to him.  Thoughts, @autodidaddict?
